---
title: "Testing"
author: "Jean Dos Santos"
date: "07/01/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Packages

```{r}
# if(!require(shiny)) {install.packages("shiny")} else {require(shiny)}
# if(!require(shinythemes)) {install.packages("shinythemes")} else {require(shinythemes)}
if(!require(GA)) {install.packages("GA")} else {require(GA)}
if(!require(tidyverse)) {install.packages("tidyverse")} else {require(tidyverse)}
if(!require(caret)) {install.packages("caret")} else {require(caret)}
# if(!require(DT)) {install.packages("DT")} else {require(DT)}
if(!require(nnet)) {install.packages("nnet")} else {require(nnet)}
if(!require(parallel)) {install.packages("parallel")} else {require(parallel)}

library(tictoc)
```


# Import Data

```{r}
features_ID <- c("Cement", "Slag", "Ash", "Water", "Superplasticizer", "Coarse_Aggregate", "Fine_Aggregate", "Age", "Strength")
features_title <- c("Cement", "Blast Furncace Slag", "Fly Ash", "Water", "Superplasticizer", "Coarse Aggregate", "Fine Aggregate", "Age (days)", "Strength (MPa)")
predictors_ID <- c("Cement", "Slag", "Ash", "Water", "Superplasticizer", "Coarse_Aggregate", "Fine_Aggregate")
age_selected <- 28 # Days of aging

if(!exists("concrete_data")) {concrete_data <- readr::read_csv("concrete_data_processed.csv", col_names = features_ID, skip = 1)}

# Import model
if(!exists("model_strength")) {model_strength <- base::readRDS("Models/avNNet_model.rds")}

# Import Functions
if(!exists("eval_function")) {eval_function <- base::source("helpers/eval_function.R")}
if(!exists("loss_function")) {loss_function <- base::source("helpers/loss_function.R")}
```

# Set Limits and mid values

```{r}
range <- concrete_data %>% 
  dplyr::select(-Age, -Strength) %>% 
  gather(key = "Parameter", value = "Value") %>% 
  group_by(Parameter) %>% 
  dplyr::summarise(min = round(min(Value),3),
                   max = round(max(Value),3),
                   mid = round(mean(Value, trim = 0.0),3))

range_matrix <- as.matrix(range[,2:4])
rownames(range_matrix) <- range$Parameter

range_matrix

Cement_range <- range_matrix["Cement", c("min", "max", "mid")]
Ash_range <- range_matrix["Ash", c("min", "max", "mid")]
Coarse_Aggregate_range <- range_matrix["Coarse_Aggregate", c("min", "max", "mid")]
Fine_Aggregate_range <- range_matrix["Fine_Aggregate", c("min", "max", "mid")]
Slag_range <- range_matrix["Slag", c("min", "max", "mid")]
Superplasticizer_range <- range_matrix["Superplasticizer", c("min", "max", "mid")]
Water_range <- range_matrix["Water", c("min", "max", "mid")]
```

```{r}
limits_GA <- data_frame(
       Cement_min = Cement_range[1],
       Cement_max = Cement_range[2],
       Ash_min = Ash_range[1],
       Ash_max = Ash_range[2],
       Coarse_Aggregate_min = Coarse_Aggregate_range[1],
       Coarse_Aggregate_max = Coarse_Aggregate_range[2],
       Fine_Aggregate_min = Fine_Aggregate_range[1],
       Fine_Aggregate_max = Fine_Aggregate_range[2],
       Slag_min = Slag_range[1],
       Slag_max = Slag_range[2],
       Superplasticizer_min = Superplasticizer_range[1],
       Superplasticizer_max = Superplasticizer_range[2],
       Water_min = Water_range[1],
       Water_max = Water_range[2],
       )

min_limits_GA <- data_frame(
       Cement = Cement_range[1],
       Ash = Ash_range[1],
       Coarse_Aggregate = Coarse_Aggregate_range[1],
       Fine_Aggregate = Fine_Aggregate_range[1],
       Slag = Slag_range[1],
       Superplasticizer = Superplasticizer_range[1],
       Water = Water_range[1]
       )

max_limits_GA <- data_frame(
       Cement = Cement_range[2],
       Ash = Ash_range[2],
       Coarse_Aggregate = Coarse_Aggregate_range[2],
       Fine_Aggregate = Fine_Aggregate_range[2],
       Slag = Slag_range[2],
       Superplasticizer = Superplasticizer_range[2],
       Water = Water_range[2]
       )

mid_values_GA <- data_frame(
       Cement = Cement_range[3],
       Ash = Ash_range[3],
       Coarse_Aggregate = Coarse_Aggregate_range[3],
       Fine_Aggregate = Fine_Aggregate_range[3],
       Slag = Slag_range[3],
       Superplasticizer = Superplasticizer_range[3],
       Water = Water_range[3]
       )

limits_GA
min_limits_GA
max_limits_GA
mid_values_GA
```

```{r}
Cement = range$mid[range$Parameter == "Cement"]
Ash = range$mid[range$Parameter == "Ash"]
Coarse_Aggregate = range$mid[range$Parameter == "Coarse_Aggregate"]
Fine_Aggregate = range$mid[range$Parameter == "Fine_Aggregate"]
Slag = range$mid[range$Parameter == "Slag"]
Superplasticizer = range$mid[range$Parameter == "Superplasticizer"]
Water = range$mid[range$Parameter == "Water"]

input_data <- tibble(
  Cement = Cement,
  Ash = Ash,
  Coarse_Aggregate = Coarse_Aggregate,
  Fine_Aggregate = Fine_Aggregate,
  Slag = Slag,
  Superplasticizer = Superplasticizer,
  Water = Water,
  Age = 28
)
```

# `eval_function`

```{r}
eval_function <- function(Cement, Ash, Coarse_Aggregate, Fine_Aggregate, Slag, Superplasticizer) {
  
  Water = 1 - sum(Cement, Ash, Coarse_Aggregate, Fine_Aggregate, Slag, Superplasticizer)

  # Create dataframe with predictors
  input_data <- tibble(
    Cement = Cement,
    Ash = Ash,
    Coarse_Aggregate = Coarse_Aggregate,
    Fine_Aggregate = Fine_Aggregate,
    Slag = Slag,
    Superplasticizer = Superplasticizer,
    Water = Water,
    Age = 28
  )
  
  # predict(model_strength, newdata = input_data)[[1]]
  
  # Create penalty score for solutions with parameters outside of range
  if (Cement >= Cement_range[1] & Cement <= Cement_range[2] &
     Ash >= Ash_range[1] & Ash <= Ash_range[2] &
     Coarse_Aggregate >= Coarse_Aggregate_range[1] & Coarse_Aggregate <= Coarse_Aggregate_range[2] &
     Fine_Aggregate >= Fine_Aggregate_range[1] & Fine_Aggregate <= Fine_Aggregate_range[2] &
     Slag >= Slag_range[1] & Slag <= Slag_range[2] &
     Superplasticizer >= Superplasticizer_range[1] & Superplasticizer <= Superplasticizer_range[2] &
     Water >= Water_range[1] & Water <= Water_range[2]) {

    predict(model_strength, newdata = input_data)[[1]]

  } else {

    -1 * if_else(Cement < Cement_range[1] | Cement > Cement_range[2], 100, 1) *
             if_else(Ash < Ash_range[1] | Ash > Ash_range[2], 100, 1) *
             if_else(Coarse_Aggregate < Coarse_Aggregate_range[1] | Coarse_Aggregate > Coarse_Aggregate_range[2], 100, 1) *
             if_else(Fine_Aggregate < Fine_Aggregate_range[1] | Fine_Aggregate > Fine_Aggregate_range[2], 100, 1) *
             if_else(Slag < Slag_range[1] | Slag > Slag_range[2], 100, 1) *
             if_else(Superplasticizer < Superplasticizer_range[1] | Superplasticizer > Superplasticizer_range[2], 100, 1) *
             if_else(Water < Water_range[1] | Water > Water_range[2], 100, 1)
    }
  
}
```

## Test function

```{r}
eval_function(Cement = Cement_range[1], Ash = Ash_range[1], Coarse_Aggregate = Coarse_Aggregate_range[1], Fine_Aggregate = Fine_Aggregate_range[1], Slag = Slag_range[1], Superplasticizer = Superplasticizer_range[1])

eval_function(Cement = Cement_range[2], Ash = Ash_range[2], Coarse_Aggregate = Coarse_Aggregate_range[2], Fine_Aggregate = Fine_Aggregate_range[2], Slag = Slag_range[2], Superplasticizer = Superplasticizer_range[2])

eval_function(Cement = Cement_range[3], Ash = Ash_range[3], Coarse_Aggregate = Coarse_Aggregate_range[3], Fine_Aggregate = Fine_Aggregate_range[3], Slag = Slag_range[3], Superplasticizer = Superplasticizer_range[3])
```

## Run ga()

```{r}
tic()
GA_output <- GA::ga(type = "real-valued",
               fitness = function(x) eval_function(x[1], x[2], x[3], x[4], x[5], x[6]),
               lower = c(min_limits_GA$Cement,
                         min_limits_GA$Ash,
                         min_limits_GA$Coarse_Aggregate,
                         min_limits_GA$Fine_Aggregate,
                         min_limits_GA$Slag,
                         min_limits_GA$Superplasticizer),
               upper = c(max_limits_GA$Cement,
                         max_limits_GA$Ash,
                         max_limits_GA$Coarse_Aggregate,
                         max_limits_GA$Fine_Aggregate,
                         max_limits_GA$Slag,
                         max_limits_GA$Superplasticizer),
               popSize = 50, # input$pop_size
               maxiter = 100, # input$max_iter,
               optim = TRUE, # input$local_search,
               seed = 1, # input$seed,
               monitor = FALSE)
toc()

GA_solution <- data.frame(
        Cement = GA_output@solution[1, 1],
        Ash = GA_output@solution[1, 2],
        Coarse_Aggregate = GA_output@solution[1, 3],
        Fine_Aggregate = GA_output@solution[1, 4],
        Slag = GA_output@solution[1, 5],
        Superplasticizer = GA_output@solution[1, 6],
        Water = 1 - sum(GA_output@solution[1,]),
        Age = age_selected,
        fitness_value = GA_output@fitnessValue
        )

GA_solution

eval_function(Cement = GA_solution$Cement, Ash = GA_solution$Ash, Coarse_Aggregate = GA_solution$Coarse_Aggregate, Fine_Aggregate = GA_solution$Fine_Aggregate, Slag = GA_solution$Slag, Superplasticizer = GA_solution$Superplasticizer)

plot(GA_output)

```

## GA_solution

```{r}
GA_solution <- data.frame(
        Cement = GA_output@solution[1, 1],
        Ash = GA_output@solution[1, 2],
        Coarse_Aggregate = GA_output@solution[1, 3],
        Fine_Aggregate = GA_output@solution[1, 4],
        Slag = GA_output@solution[1, 5],
        Superplasticizer = GA_output@solution[1, 6],
        Water = 1 - sum(GA_output@solution[1,]),
        Age = age_selected,
        fitness_value = GA_output@fitnessValue
        )

GA_solution
```


# `eval_function_with_limits`

```{r}
eval_function_with_limits <- function(Cement, Ash, Coarse_Aggregate, Fine_Aggregate, Slag, Superplasticizer, min_limits_GA, max_limits_GA) {
  
  Water = 1 - sum(Cement, Ash, Coarse_Aggregate, Fine_Aggregate, Slag, Superplasticizer)

  # Create dataframe with predictors
  input_data <- tibble(
    Cement = Cement,
    Ash = Ash,
    Coarse_Aggregate = Coarse_Aggregate,
    Fine_Aggregate = Fine_Aggregate,
    Slag = Slag,
    Superplasticizer = Superplasticizer,
    Water = Water,
    Age = 28
  )
  
  # predict(model_strength, newdata = input_data)[[1]]
  
  # Create penalty score for solutions with parameters outside of range
  if (Cement >= min_limits_GA$Cement & Cement <= max_limits_GA$Cement &
     Ash >= min_limits_GA$Ash & Ash <= max_limits_GA$Ash &
     Coarse_Aggregate >= min_limits_GA$Coarse_Aggregate & Coarse_Aggregate <= max_limits_GA$Coarse_Aggregate &
     Fine_Aggregate >= min_limits_GA$Fine_Aggregate & Fine_Aggregate <= max_limits_GA$Fine_Aggregate &
     Slag >= min_limits_GA$Slag & Slag <= max_limits_GA$Slag &
     Superplasticizer >= min_limits_GA$Superplasticizer & Superplasticizer <= max_limits_GA$Superplasticizer &
     Water >= min_limits_GA$Water & Water <= max_limits_GA$Water) {

    predict(model_strength, newdata = input_data)[[1]]

  } else {

    -1 * if_else(Cement < min_limits_GA$Cement | Cement > max_limits_GA$Cement, 100, 1) *
             if_else(Ash < min_limits_GA$Ash | Ash > max_limits_GA$Ash, 100, 1) *
             if_else(Coarse_Aggregate < min_limits_GA$Coarse_Aggregate | Coarse_Aggregate > max_limits_GA$Coarse_Aggregate, 100, 1) *
             if_else(Fine_Aggregate < min_limits_GA$Fine_Aggregate | Fine_Aggregate > max_limits_GA$Fine_Aggregate, 100, 1) *
             if_else(Slag < min_limits_GA$Slag | Slag > max_limits_GA$Slag, 100, 1) *
             if_else(Superplasticizer < min_limits_GA$Superplasticizer | Superplasticizer > max_limits_GA$Superplasticizer, 100, 1) *
             if_else(Water < min_limits_GA$Water | Water > max_limits_GA$Water, 100, 1)
    }
  
}
```

## Test function

```{r}
min_limits_GA <- data_frame(
       Cement = min(concrete_data$Cement),
       Ash = min(concrete_data$Ash),
       Coarse_Aggregate = min(concrete_data$Coarse_Aggregate),
       Fine_Aggregate = min(concrete_data$Fine_Aggregate),
       Slag = min(concrete_data$Slag),
       Superplasticizer = min(concrete_data$Superplasticizer),
       Water = min(concrete_data$Water)
       )

max_limits_GA <- data_frame(
       Cement = max(concrete_data$Cement),
       Ash = max(concrete_data$Ash),
       Coarse_Aggregate = max(concrete_data$Coarse_Aggregate),
       Fine_Aggregate = max(concrete_data$Fine_Aggregate),
       Slag = max(concrete_data$Slag),
       Superplasticizer = max(concrete_data$Superplasticizer),
       Water = max(concrete_data$Water)
       )

eval_function_with_limits(Cement = Cement_range[1], Ash = Ash_range[1], Coarse_Aggregate = Coarse_Aggregate_range[1], Fine_Aggregate = Fine_Aggregate_range[1], Slag = Slag_range[1], Superplasticizer = Superplasticizer_range[1], min_limits_GA = min_limits_GA, max_limits_GA = max_limits_GA)

eval_function_with_limits(Cement = Cement_range[2], Ash = Ash_range[2], Coarse_Aggregate = Coarse_Aggregate_range[2], Fine_Aggregate = Fine_Aggregate_range[2], Slag = Slag_range[2], Superplasticizer = Superplasticizer_range[2], min_limits_GA = min_limits_GA, max_limits_GA = max_limits_GA)

eval_function_with_limits(Cement = Cement_range[3], Ash = Ash_range[3], Coarse_Aggregate = Coarse_Aggregate_range[3], Fine_Aggregate = Fine_Aggregate_range[3], Slag = Slag_range[3], Superplasticizer = Superplasticizer_range[3], min_limits_GA = min_limits_GA, max_limits_GA = max_limits_GA)
```

## Run ga()

```{r}
tic()
GA_output <- GA::ga(type = "real-valued",
               fitness = function(x) eval_function_with_limits(x[1], x[2], x[3], x[4], x[5], x[6], 
                                                               min_limits_GA = min_limits_GA, 
                                                               max_limits_GA = max_limits_GA),
               lower = c(min_limits_GA$Cement,
                         min_limits_GA$Ash,
                         min_limits_GA$Coarse_Aggregate,
                         min_limits_GA$Fine_Aggregate,
                         min_limits_GA$Slag,
                         min_limits_GA$Superplasticizer),
               upper = c(max_limits_GA$Cement,
                         max_limits_GA$Ash,
                         max_limits_GA$Coarse_Aggregate,
                         max_limits_GA$Fine_Aggregate,
                         max_limits_GA$Slag,
                         max_limits_GA$Superplasticizer),
               popSize = 50, # input$pop_size
               maxiter = 100, # input$max_iter,
               optim = TRUE, # input$local_search,
               seed = 1, # input$seed,
               monitor = FALSE)
toc()

GA_output@solution[1,]

GA_solution <- data.frame(
        Cement = GA_output@solution[1, 1],
        Ash = GA_output@solution[1, 2],
        Coarse_Aggregate = GA_output@solution[1, 3],
        Fine_Aggregate = GA_output@solution[1, 4],
        Slag = GA_output@solution[1, 5],
        Superplasticizer = GA_output@solution[1, 6],
        Water = 1 - sum(GA_output@solution[1,]),
        Age = age_selected,
        fitness_value = GA_output@fitnessValue
        )

GA_solution

predict(model_strength, newdata = GA_solution[, model_strength$finalModel$coefnames])

plot(GA_output)

```



## GA_solution

```{r}
GA_solution <- data.frame(
        Cement = GA_output@solution[1, 1],
        Ash = GA_output@solution[1, 2],
        Coarse_Aggregate = GA_output@solution[1, 3],
        Fine_Aggregate = GA_output@solution[1, 4],
        Slag = GA_output@solution[1, 5],
        Superplasticizer = GA_output@solution[1, 6],
        Water = 1 - sum(GA_output@solution[1,]),
        fitness_value = GA_output@fitnessValue
        )

GA_solution
```



```{r}
tibble(x = 1, x = 2, .name_repair = ~ c("a", "b"))
```































































































